import Link from "next/link";
import { ContentPage } from "../lib/content-registry";
import { SiteFooter, SiteHeader } from "./site-chrome";
import { siteUrl } from "../lib/site-config";

export function ContentPageView({ page, kind }: { page: ContentPage; kind: "guide" | "format" | "platform" }) {
  const canonical = `${siteUrl}/${kind}/${page.slug}`;
  const jsonLd = { "@context": "https://schema.org", "@graph": [{ "@type": kind === "format" ? "TechArticle" : "Article", "@id": `${canonical}#article`, headline: page.title, description: page.description, datePublished: page.lastReviewed, dateModified: page.lastReviewed, inLanguage: "en", articleSection: page.eyebrow, image: `${siteUrl}/opengraph-image`, author: { "@type": "Organization", name: "vCard Editor", url: `${siteUrl}/author` }, mainEntityOfPage: canonical, publisher: { "@type": "Organization", name: "vCard Editor", url: siteUrl, logo: { "@type": "ImageObject", url: `${siteUrl}/icon.svg` } } }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteUrl }, { "@type": "ListItem", position: 2, name: kind === "guide" ? "Guides" : kind === "format" ? "Formats" : "Platform workflows", item: `${siteUrl}/${kind}` }, { "@type": "ListItem", position: 3, name: page.title, item: canonical }] }, ...(page.faqs?.length ? [{ "@type": "FAQPage", mainEntity: page.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }] : [])] };
  return <main><SiteHeader /><article className="content-page" id="content"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">/</span><Link href={`/${kind}`}>{kind === "guide" ? "Guides" : kind === "format" ? "Formats" : "Platform workflows"}</Link><span aria-hidden="true">/</span><span aria-current="page">{page.title}</span></nav><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p className="content-intro">{page.intro}</p><p className="reviewed">Last reviewed <time dateTime={page.lastReviewed}>{page.lastReviewed}</time></p>{page.answer && <section className="direct-answer" aria-labelledby="answer-heading"><p className="eyebrow">DIRECT ANSWER</p><h2 id="answer-heading">What you should know</h2><p>{page.answer}</p></section>}{page.targetTool && <Link className="content-cta" href={page.targetTool}>Open the related tool <span aria-hidden="true">↗</span></Link>}{page.checklist && <section className="content-checklist" aria-labelledby="checklist-heading"><h2 id="checklist-heading">Before you begin</h2><ul>{page.checklist.map((item) => <li key={item}>{item}</li>)}</ul></section>}<div className="content-body">{page.sections.map((section) => <section key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.steps && <ol>{section.steps.map((step) => <li key={step}>{step}</li>)}</ol>}</section>)}</div>{page.faqs && page.faqs.length > 0 && <section className="content-faq" aria-labelledby="faq-heading"><h2 id="faq-heading">Questions people ask</h2>{page.faqs.map((faq) => <details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</section>}{page.sources && page.sources.length > 0 && <section className="content-sources" aria-labelledby="sources-heading"><h2 id="sources-heading">References</h2><ul>{page.sources.map((source) => <li key={source.href}><a href={source.href} target="_blank" rel="noopener noreferrer">{source.label}</a></li>)}</ul></section>}{page.related.length > 0 && <aside className="related-content" aria-labelledby="related-heading"><h2 id="related-heading">Related tools and guides</h2><div>{page.related.map((related) => <Link href={related.href} key={related.href}>{related.label}<span aria-hidden="true">↗</span></Link>)}</div></aside>}<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /></article><SiteFooter /></main>;
}
