"use client";

import { ChangeEvent, useMemo, useRef, useState } from "react";
import { guardFile } from "../lib/file-guard";
import { findFuzzyMatches } from "../lib/fuzzy";
import { decodeVCardBytes, parseVCard, type Contact } from "../lib/vcard";

function download(value: string, name: string) { const url = URL.createObjectURL(new Blob([value], { type: "text/plain;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
function summary(contact: Contact) { return [contact.formattedName || "Unnamed contact", contact.organisation, contact.phones.join(", "), contact.emails.join(", ")].filter(Boolean); }

export default function FuzzyWorkspace() {
  const inputRef = useRef<HTMLInputElement>(null); const [contacts, setContacts] = useState<Contact[]>([]); const [fileName, setFileName] = useState(""); const [threshold, setThreshold] = useState(0.72); const [status, setStatus] = useState("Choose a VCF file");
  const result = useMemo(() => findFuzzyMatches(contacts, threshold), [contacts, threshold]);
  function handleFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; const guard = guardFile(file, [".vcf", ".vcard"]); if (!guard.ok) { setStatus(guard.message); return; } file.arrayBuffer().then((buffer) => { const parsed = parseVCard(decodeVCardBytes(buffer).text); setContacts(parsed.contacts); setFileName(file.name); setStatus(`${parsed.contacts.length.toLocaleString()} contacts analysed with bounded candidate matching`); }).catch(() => setStatus("That file could not be read.")); }
  function exportReport() { const report = ["Fuzzy contact match review", `Contacts: ${contacts.length}`, `Threshold: ${Math.round(threshold * 100)}%`, `Candidate comparisons: ${result.comparisons}`, "", ...result.matches.flatMap((match, index) => [`${index + 1}. ${match.score}% · ${match.reasons.join(", ") || "combined similarity"}`, `   A: ${summary(match.left).join(" · ")}`, `   B: ${summary(match.right).join(" · ")}`, ""])].join("\n"); download(report, `${fileName.replace(/\.(vcf|vcard)$/i, "") || "contacts"}-fuzzy-matches.txt`); }
  return <div className="conversion-card"><div className="conversion-toolbar"><span className="file-icon" aria-hidden="true">≈</span><div><strong>{fileName || "Fuzzy contact matcher"}</strong><small aria-live="polite">{status}</small></div>{contacts.length > 0 && <button className="primary-button compact" onClick={exportReport}>Download report <span>↓</span></button>}</div>{!contacts.length ? <div className="conversion-dropzone"><div className="drop-icon" aria-hidden="true">↥</div><h2>Find likely duplicate contacts</h2><p>Candidate blocking avoids an expensive all-pairs scan. Nothing is merged automatically.</p><button className="primary-button" onClick={() => inputRef.current?.click()}>Choose VCF <span>⌘</span></button><input ref={inputRef} type="file" accept=".vcf,.vcard,text/vcard" onChange={handleFile} hidden aria-label="Choose a VCF file" /></div> : <section className="preview-section"><div className="preview-heading"><div><p className="eyebrow">REVIEW-FIRST MATCHES</p><h2>{result.matches.length.toLocaleString()} possible pairs</h2></div><label className="mapping-tools">Sensitivity<select value={threshold} onChange={(event) => setThreshold(Number(event.target.value))}><option value={0.82}>Conservative</option><option value={0.72}>Balanced</option><option value={0.64}>Broad review</option></select></label></div>{result.capped && <div className="conversion-warning"><strong>Candidate limit reached</strong><span>The report stopped after 50,000 bounded comparisons. Use conservative mode or split the file for a fuller review.</span></div>}<div className="match-list">{result.matches.slice(0, 100).map((match) => <article key={`${match.left.id}-${match.right.id}`}><header><strong>{match.score}% likely match</strong><span>{match.reasons.join(" · ") || "combined similarity"}</span></header><div><section>{summary(match.left).map((value) => <span key={value}>{value}</span>)}</section><b aria-hidden="true">⇄</b><section>{summary(match.right).map((value) => <span key={value}>{value}</span>)}</section></div></article>)}{!result.matches.length && <p className="empty-preview">No candidate pairs met this threshold.</p>}</div><p className="mapping-note">Scores are review signals, not identity claims. Shared household numbers and similar names can belong to different people.</p></section>}</div>;
}
