"use client";

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { zipSync } from "fflate";
import { guardFile } from "../lib/file-guard";
import { bytesToDataUri, embeddedPhoto, safePhotoFileName } from "../lib/photos";
import { decodeVCardBytes, parseVCard, serializeVCards, type Contact } from "../lib/vcard";

function download(content: BlobPart, name: string, type: string) { const url = URL.createObjectURL(new Blob([content], { type })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }

async function resizePhoto(contact: Contact, maxDimension: number, quality: number) {
  const photo = embeddedPhoto(contact); if (!photo) return contact;
  const bitmap = await createImageBitmap(new Blob([photo.bytes], { type: photo.type }));
  try {
    const scale = Math.min(1, maxDimension / Math.max(bitmap.width, bitmap.height));
    const width = Math.max(1, Math.round(bitmap.width * scale)); const height = Math.max(1, Math.round(bitmap.height * scale));
    const canvas = document.createElement("canvas"); canvas.width = width; canvas.height = height;
    const context = canvas.getContext("2d", { alpha: false }); if (!context) throw new Error("Canvas is unavailable.");
    context.fillStyle = "#fff"; context.fillRect(0, 0, width, height); context.drawImage(bitmap, 0, 0, width, height);
    const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/jpeg", quality)); if (!blob) throw new Error("Photo compression failed.");
    const bytes = new Uint8Array(await blob.arrayBuffer());
    return { ...contact, photo: bytesToDataUri(bytes, "image/jpeg"), photoType: "image/jpeg" };
  } finally { bitmap.close(); }
}

export default function PhotoWorkspace({ mode }: { mode: "compress" | "extract" | "view" }) {
  const inputRef = useRef<HTMLInputElement>(null); const cancelled = useRef(false); const [contacts, setContacts] = useState<Contact[]>([]); const [fileName, setFileName] = useState(""); const [status, setStatus] = useState("Choose a VCF file"); const [busy, setBusy] = useState(false); const [maxDimension, setMaxDimension] = useState(512); const [quality, setQuality] = useState(0.82);
  const photos = useMemo(() => contacts.flatMap((contact, index) => { try { const photo = embeddedPhoto(contact); return photo ? [{ contact, index, photo }] : []; } catch { return []; } }), [contacts]);
  const previews = useMemo(() => photos.slice(0, 12).map(({ contact, photo, index }) => ({ name: contact.formattedName || `Contact ${index + 1}`, url: URL.createObjectURL(new Blob([photo.bytes], { type: photo.type })) })), [photos]);
  useEffect(() => () => previews.forEach((preview) => URL.revokeObjectURL(preview.url)), [previews]);
  function handleFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; const guard = guardFile(file, [".vcf", ".vcard"]); if (!guard.ok) { setStatus(guard.message); return; } file.arrayBuffer().then((buffer) => { const parsed = parseVCard(decodeVCardBytes(buffer).text); setContacts(parsed.contacts); setFileName(file.name); const count = parsed.contacts.filter((contact) => contact.photo).length; setStatus(`${count.toLocaleString()} embedded photo value${count === 1 ? "" : "s"} found`); }).catch(() => setStatus("That file could not be read.")); }
  function extract() { const files: Record<string, Uint8Array> = {}; let rejected = 0; contacts.forEach((contact, index) => { try { const photo = embeddedPhoto(contact); if (photo) files[safePhotoFileName(contact, index, photo.extension)] = photo.bytes; else if (contact.photo) rejected += 1; } catch { rejected += 1; } }); if (!Object.keys(files).length) { setStatus("No safe embedded photos were available to extract."); return; } download(zipSync(files) as unknown as ArrayBuffer, `${fileName.replace(/\.(vcf|vcard)$/i, "") || "contacts"}-photos.zip`, "application/zip"); setStatus(`Extracted ${Object.keys(files).length.toLocaleString()} photos${rejected ? ` · ${rejected} unsafe or remote values skipped` : ""}`); }
  async function compress() { if (busy) return; setBusy(true); cancelled.current = false; const output: Contact[] = []; let changed = 0; let skipped = 0; for (let index = 0; index < contacts.length; index += 1) { if (cancelled.current) { setStatus("Compression cancelled. No output was downloaded."); setBusy(false); return; } const contact = contacts[index]; setStatus(`Compressing contact ${index + 1} of ${contacts.length}…`); try { const next = await resizePhoto(contact, maxDimension, quality); output.push(next); if (next.photo !== contact.photo) changed += 1; } catch { output.push(contact); if (contact.photo) skipped += 1; } await new Promise((resolve) => window.setTimeout(resolve, 0)); } download(serializeVCards(output, { version: "3.0", preserveUnknown: true, includePhotos: true }), `${fileName.replace(/\.(vcf|vcard)$/i, "") || "contacts"}-compressed.vcf`, "text/vcard;charset=utf-8"); setStatus(`Compressed ${changed.toLocaleString()} photos${skipped ? ` · ${skipped} unsupported values preserved` : ""}`); setBusy(false); }
  const title = mode === "compress" ? "Compress contact photos" : mode === "extract" ? "Extract contact photos" : "Contact photo viewer";
  return <div className="conversion-card"><div className="conversion-toolbar"><span className="file-icon" aria-hidden="true">IMG</span><div><strong>{fileName || title}</strong><small aria-live="polite">{status}</small></div>{contacts.length > 0 && mode === "extract" && <button className="primary-button compact" onClick={extract}>Download ZIP <span>↓</span></button>}{contacts.length > 0 && mode === "compress" && <>{busy ? <button className="secondary-button" onClick={() => { cancelled.current = true; }}>Cancel</button> : <button className="primary-button compact" onClick={compress}>Compress &amp; download <span>↓</span></button>}</>}</div>{!contacts.length ? <div className="conversion-dropzone"><div className="drop-icon" aria-hidden="true">↥</div><h2>Choose a VCF with embedded photos</h2><p>Only validated embedded image bytes are decoded. Remote photo URLs are never fetched.</p><button className="primary-button" onClick={() => inputRef.current?.click()}>Choose VCF <span>⌘</span></button><input ref={inputRef} type="file" accept=".vcf,.vcard,text/vcard" onChange={handleFile} hidden aria-label="Choose a VCF file" /></div> : <section className="preview-section"><div className="preview-heading"><div><p className="eyebrow">SAFE PHOTO PREVIEW</p><h2>{photos.length.toLocaleString()} validated images</h2></div><button className="secondary-button" onClick={() => { setContacts([]); setFileName(""); }}>Open another</button></div>{mode === "compress" && <div className="cleaner-options"><label>Maximum dimension<select value={maxDimension} onChange={(event) => setMaxDimension(Number(event.target.value))}><option value={256}>256 px</option><option value={512}>512 px</option><option value={1024}>1024 px</option></select></label><label>JPEG quality<select value={quality} onChange={(event) => setQuality(Number(event.target.value))}><option value={0.7}>Smaller</option><option value={0.82}>Balanced</option><option value={0.92}>Higher quality</option></select></label></div>}<div className="photo-grid">{previews.map((preview) => <figure key={preview.url}><img src={preview.url} alt="" /><figcaption>{preview.name}</figcaption></figure>)}</div>{!photos.length && <p className="empty-preview">No safe JPEG, PNG, GIF, or WebP photos could be previewed. Remote URLs and invalid payloads were skipped.</p>}</section>}</div>;
}
