"use client";

import { ChangeEvent, useState } from "react";
import { guardFile } from "../lib/file-guard";
import { decodeVCardBytes, KnownVCardVersion, parseVCard, serializeVCards } from "../lib/vcard";
import { repairVCardText } from "../lib/contact-tools";
import { trackEvent } from "../lib/analytics";

export default function VCardTransformWorkspace({ mode }: { mode: "version" | "encoding" }) {
  const [input, setInput] = useState(""); const [fileName, setFileName] = useState(""); const [target, setTarget] = useState<KnownVCardVersion>("3.0"); const [output, setOutput] = useState(""); const [status, setStatus] = useState("Choose a VCF file to begin"); const [repairs, setRepairs] = useState<string[]>([]);
  function run(text = input) { if (!text.trim()) { setStatus("Choose a VCF file or paste vCard text first"); return; } try { if (mode === "encoding") { const result = repairVCardText(text, target); setOutput(result.output); setRepairs(result.repairs); setStatus(`${result.parsed.contacts.length.toLocaleString()} contacts repaired and ready`); } else { const parsed = parseVCard(text); setOutput(serializeVCards(parsed.contacts, { version: target, preserveUnknown: true, includePhotos: true })); setRepairs([`Converted ${parsed.contacts.length.toLocaleString()} contacts to vCard ${target}.`, ...parsed.warnings]); setStatus(`${parsed.contacts.length.toLocaleString()} contacts converted to vCard ${target}`); } trackEvent("tool_run_succeeded", { tool_slug: mode === "version" ? "vcard-version-converter" : "vcf-encoding-fixer", output_format: "vcf" }); } catch { setOutput(""); setStatus("The VCF could not be processed. The original remains unchanged."); trackEvent("tool_run_failed", { tool_slug: mode === "version" ? "vcard-version-converter" : "vcf-encoding-fixer", error_code: "invalid-vcf" }); } }
  function handleFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; const guard = guardFile(file, [".vcf", ".vcard"]); if (!guard.ok) { setStatus(guard.message); return; } const reader = new FileReader(); reader.onload = () => { if (reader.result instanceof ArrayBuffer) { const text = decodeVCardBytes(reader.result).text; setInput(text); setFileName(file.name); run(text); } }; reader.onerror = () => setStatus("Could not read that file"); reader.readAsArrayBuffer(file); trackEvent("file_selected", { tool_slug: mode === "version" ? "vcard-version-converter" : "vcf-encoding-fixer", input_format: "vcf", size_bucket: file.size > 8 * 1024 * 1024 ? "large" : "standard" }); }
  function download() { const blob = new Blob([output], { type: "text/vcard;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${fileName.replace(/\.(vcf|vcard)$/i, "") || "contacts"}-${mode === "encoding" ? "encoding-fixed" : `v${target}`}.vcf`; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); trackEvent("download_clicked", { tool_slug: mode === "version" ? "vcard-version-converter" : "vcf-encoding-fixer", output_format: "vcf" }); }
  return <div className="conversion-card"><div className="conversion-toolbar"><span className="file-icon">VCF</span><div><strong>{fileName || (mode === "version" ? "vCard Version Converter" : "VCF Encoding Fixer")}</strong><small aria-live="polite">{status}</small></div>{output && <button className="primary-button compact" onClick={download}>Download VCF <span>↓</span></button>}</div><div className="mapping-section"><div className="mapping-heading"><div><p className="eyebrow">{mode === "version" ? "VERSION CONVERTER" : "ENCODING FIXER"}</p><h2>{mode === "version" ? "Choose a compatible output version." : "Repair common encoding and line-ending problems."}</h2></div><label className="mapping-tools">Target version<select value={target} onChange={(event) => setTarget(event.target.value as KnownVCardVersion)}><option value="2.1">vCard 2.1</option><option value="3.0">vCard 3.0</option><option value="4.0">vCard 4.0</option></select></label></div><textarea className="standards-input" value={input} onChange={(event) => setInput(event.target.value)} rows={11} placeholder="Paste vCard text or choose a file" spellCheck={false} /><div className="export-actions"><label className="secondary-button">Choose VCF<input type="file" accept=".vcf,.vcard,text/vcard" onChange={handleFile} hidden /></label><button className="primary-button compact" onClick={() => run()}>Process locally <span>→</span></button></div></div>{repairs.length > 0 && <section className="operation-section"><div className="operation-heading"><div><p className="eyebrow">CHANGE SUMMARY</p><h2>{repairs.length} item{repairs.length === 1 ? "" : "s"} recorded</h2></div></div><div className="issue-list">{repairs.map((repair, index) => <div key={`${repair}-${index}`}><span className="issue-severity issue-warning">info</span><span>{repair}</span></div>)}</div></section>}{output && <section className="preview-section"><div className="preview-heading"><div><p className="eyebrow">OUTPUT PREVIEW</p><h2>Ready to download</h2></div></div><textarea className="standards-output" value={output} readOnly rows={10} spellCheck={false} /></section>}</div>;
}

