"use client";

import { useMemo, useState } from "react";
import { KnownVCardVersion, serializeVCards, Contact } from "../lib/vcard";
import { trackEvent } from "../lib/analytics";

function blankContact(values: Partial<Contact>): Contact {
  return { id: "new-contact", version: "3.0", firstName: "", lastName: "", formattedName: "", phones: [], emails: [], organisation: "", title: "", note: "", uid: "", categories: [], photo: "", rawProperties: [], properties: [], issues: [], ...values };
}

export default function VCardCreator() {
  const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState(""); const [phone, setPhone] = useState(""); const [email, setEmail] = useState(""); const [organisation, setOrganisation] = useState(""); const [title, setTitle] = useState(""); const [note, setNote] = useState(""); const [nickname, setNickname] = useState(""); const [address, setAddress] = useState(""); const [url, setUrl] = useState(""); const [birthday, setBirthday] = useState(""); const [version, setVersion] = useState<KnownVCardVersion>("3.0");
  const contact = useMemo(() => blankContact({ firstName, lastName, formattedName: [firstName, lastName].filter(Boolean).join(" "), phones: phone.split(/[,\n]/).map((value) => value.trim()).filter(Boolean), emails: email.split(/[,\n]/).map((value) => value.trim()).filter(Boolean), organisation, title, note, nickname, address, url, birthday, version }), [firstName, lastName, phone, email, organisation, title, note, nickname, address, url, birthday, version]);
  const output = useMemo(() => serializeVCards([contact], { version, preserveUnknown: false, includePhotos: false }), [contact, version]);
  function sample() { setFirstName("Ada"); setLastName("Okafor"); setPhone("+234 801 234 5678"); setEmail("ada@example.test"); setOrganisation("Northstar Studio"); setTitle("Product designer"); setNickname("Ada"); setAddress("42 Example Street;Lagos;;100001;Nigeria"); setUrl("https://example.test/ada"); setBirthday("1990-01-01"); trackEvent("sample_loaded", { tool_slug: "vcard-creator", source: "sample" }); }
  function download() { const blob = new Blob([output], { type: "text/vcard;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${contact.formattedName.replace(/[^a-z0-9]+/gi, "-").toLowerCase() || "contact"}.vcf`; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); trackEvent("download_clicked", { tool_slug: "vcard-creator", output_format: "vcf" }); }
  return <div className="creator-card"><div className="creator-toolbar"><span className="file-icon">VCF</span><div><strong>Create a contact</strong><small>Build one vCard locally, then download it.</small></div><button className="text-button" onClick={sample}>Try a sample</button><button className="primary-button compact" onClick={download} disabled={!contact.formattedName && !phone && !email}>Download VCF <span>↓</span></button></div><div className="creator-grid"><section className="creator-form"><p className="eyebrow">CONTACT DETAILS</p><div className="form-grid"><label>First name<input value={firstName} onChange={(event) => setFirstName(event.target.value)} /></label><label>Last name<input value={lastName} onChange={(event) => setLastName(event.target.value)} /></label><label>Nickname<input value={nickname} onChange={(event) => setNickname(event.target.value)} /></label><label>Job title<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="wide">Phone(s)<input value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="Separate multiple values with commas" /></label><label className="wide">Email(s)<input value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Separate multiple values with commas" /></label><label>Organisation<input value={organisation} onChange={(event) => setOrganisation(event.target.value)} /></label><label>Website<input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://…" /></label><label className="wide">Address<input value={address} onChange={(event) => setAddress(event.target.value)} placeholder="Street;City;Region;Postal;Country" /></label><label>Birthday<input type="date" value={birthday} onChange={(event) => setBirthday(event.target.value)} /></label><label className="wide">Note<textarea value={note} onChange={(event) => setNote(event.target.value)} rows={3} /></label><label className="wide">Output version<select value={version} onChange={(event) => setVersion(event.target.value as KnownVCardVersion)}><option value="2.1">vCard 2.1</option><option value="3.0">vCard 3.0</option><option value="4.0">vCard 4.0</option></select></label></div></section><section className="creator-preview"><p className="eyebrow">RAW PREVIEW</p><pre>{output}</pre><p className="mapping-note">Values are escaped and generated in your browser. No contact data is uploaded.</p></section></div></div>;
}
