"use client";

import { ChangeEvent, useMemo, useRef, useState } from "react";
import { zipSync } from "fflate";
import { trackEvent } from "../lib/analytics";
import { guardFile } from "../lib/file-guard";
import { encodeQr, qrToSvg } from "../lib/qr";
import { decodeVCardBytes, parseVCard, serializeVCards } from "../lib/vcard";

function download(content: BlobPart, name: string, type: string) { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }

export default function VCardQrWorkspace({ mode }: { mode: "single" | "batch" }) {
  const inputRef = useRef<HTMLInputElement>(null); const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState(""); const [phone, setPhone] = useState(""); const [email, setEmail] = useState(""); const [organisation, setOrganisation] = useState(""); const [raw, setRaw] = useState(""); const [fileName, setFileName] = useState(""); const [status, setStatus] = useState("Create a contact or choose a VCF file");
  const contactText = useMemo(() => `BEGIN:VCARD\nVERSION:3.0\nN:${lastName};${firstName};;;\nFN:${[firstName, lastName].filter(Boolean).join(" ")}\n${phone ? `TEL;TYPE=CELL:${phone}\n` : ""}${email ? `EMAIL;TYPE=INTERNET:${email}\n` : ""}${organisation ? `ORG:${organisation}\n` : ""}END:VCARD`, [firstName, lastName, phone, email, organisation]);
  const svg = useMemo(() => { if (mode !== "single" || (!firstName && !lastName && !phone && !email)) return ""; try { return qrToSvg(contactText); } catch { return ""; } }, [contactText, email, firstName, lastName, mode, phone]);
  const parsed = useMemo(() => raw ? parseVCard(raw) : null, [raw]);

  function loadSample() { setFirstName("Ada"); setLastName("Okafor"); setPhone("+234 801 234 5678"); setEmail("ada@example.test"); setOrganisation("Northstar Studio"); setStatus("QR preview ready"); trackEvent("sample_loaded", { tool_slug: mode === "single" ? "vcard-qr-code" : "vcf-to-qr-codes", source: "sample" }); }
  function handleFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const guard = guardFile(file, [".vcf", ".vcard"]); if (!guard.ok) { setStatus(guard.message); return; } const reader = new FileReader(); reader.onload = () => { if (!(reader.result instanceof ArrayBuffer)) return; const decoded = decodeVCardBytes(reader.result); setRaw(decoded.text); setFileName(file.name); setStatus(`${parseVCard(decoded.text).contacts.length.toLocaleString()} contacts ready`); }; reader.readAsArrayBuffer(file); event.target.value = ""; }
  function downloadSingle() { if (!svg) return; download(svg, "contact-qr.svg", "image/svg+xml;charset=utf-8"); download(contactText, "contact.vcf", "text/vcard;charset=utf-8"); trackEvent("download_clicked", { tool_slug: "vcard-qr-code", output_format: "svg" }); }
  function downloadBatch() { if (!parsed?.contacts.length) return; const files: Record<string, Uint8Array> = {}; parsed.contacts.forEach((contact, index) => { try { const text = serializeVCards([contact], { version: "3.0", preserveUnknown: true }); const code = qrToSvg(text); const name = (contact.formattedName || `contact-${index + 1}`).replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase() || `contact-${index + 1}`; files[`${String(index + 1).padStart(4, "0")}-${name}.svg`] = new TextEncoder().encode(code); } catch { /* an overlong card is reported below */ } }); if (!Object.keys(files).length) { setStatus("No contacts fit the local QR size limit."); return; } download(zipSync(files) as unknown as ArrayBuffer, `${fileName.replace(/\.(vcf|vcard)$/i, "") || "contacts"}-qr.zip`, "application/zip"); trackEvent("download_clicked", { tool_slug: "vcf-to-qr-codes", output_format: "zip", contact_count_bucket: parsed.contacts.length > 1000 ? "1000-plus" : parsed.contacts.length > 100 ? "101-1000" : "0-100" }); setStatus(`Downloaded ${Object.keys(files).length.toLocaleString()} QR codes`); }

  return <div className="creator-card"><div className="creator-toolbar"><span className="file-icon">QR</span><div><strong>{mode === "single" ? "vCard QR code" : "VCF to QR codes"}</strong><small aria-live="polite">{status} · generated locally</small></div><button className="text-button" onClick={loadSample}>Try a sample</button>{mode === "single" ? <button className="primary-button compact" onClick={downloadSingle} disabled={!svg}>Download QR <span>↓</span></button> : <button className="primary-button compact" onClick={downloadBatch} disabled={!parsed?.contacts.length}>Download ZIP <span>↓</span></button>}</div>{mode === "single" ? <div className="creator-grid"><section className="creator-form"><p className="eyebrow">CONTACT DETAILS</p><div className="form-grid"><label>First name<input value={firstName} onChange={(event) => setFirstName(event.target.value)} /></label><label>Last name<input value={lastName} onChange={(event) => setLastName(event.target.value)} /></label><label className="wide">Phone<input value={phone} onChange={(event) => setPhone(event.target.value)} /></label><label className="wide">Email<input value={email} onChange={(event) => setEmail(event.target.value)} /></label><label className="wide">Organisation<input value={organisation} onChange={(event) => setOrganisation(event.target.value)} /></label></div><p className="mapping-note">The QR contains an ordinary vCard payload. No contact data is uploaded.</p></section><section className="creator-preview"><p className="eyebrow">QR PREVIEW</p>{svg ? <div className="qr-preview" dangerouslySetInnerHTML={{ __html: svg }} /> : <p className="empty-preview">Add a name, phone, or email to preview a QR code.</p>}<pre>{contactText}</pre></section></div> : <>{!raw ? <div className="conversion-dropzone"><div className="drop-icon" aria-hidden="true">↥</div><h2>Choose a VCF file</h2><p>Generate one QR SVG per contact and download them as a ZIP.</p><div className="drop-actions"><button className="primary-button" onClick={() => inputRef.current?.click()}>Choose VCF <span>⌘</span></button><button className="text-button" onClick={loadSample}>Try a sample</button></div><input ref={inputRef} type="file" accept=".vcf,.vcard,text/vcard" onChange={handleFile} hidden /><small>Local processing · no contact data upload</small></div> : <section className="preview-section"><div className="preview-heading"><div><p className="eyebrow">QR BATCH PREVIEW</p><h2>{parsed?.contacts.length.toLocaleString()} contacts</h2></div><button className="secondary-button" onClick={() => { setRaw(""); setFileName(""); }}>Open another</button></div><p className="mapping-note">Each contact becomes a standalone SVG in a ZIP. Very long cards may exceed the compact QR capacity and are skipped with a local status message.</p></section>}</>}</div>;
}
