"use client";

import { ChangeEvent, useMemo, useState } from "react";
import { guardFile } from "../lib/file-guard";
import { decodeVCardBytes, parseVCard } from "../lib/vcard";
import { trackEvent } from "../lib/analytics";

type Side = { name: string; text: string };
const keyFor = (contact: ReturnType<typeof parseVCard>["contacts"][number]) => `${contact.uid}|${contact.formattedName.toLowerCase()}|${contact.emails.map((value) => value.toLowerCase()).join(",")}|${contact.phones.join(",")}`;

export default function VcfCompareWorkspace() {
  const [left, setLeft] = useState<Side | null>(null); const [right, setRight] = useState<Side | null>(null); const [status, setStatus] = useState("Choose two VCF files to compare");
  const comparison = useMemo(() => { if (!left || !right) return null; const a = parseVCard(left.text).contacts; const b = parseVCard(right.text).contacts; const aKeys = new Set(a.map(keyFor)); const bKeys = new Set(b.map(keyFor)); return { a: a.length, b: b.length, added: b.filter((contact) => !aKeys.has(keyFor(contact))), removed: a.filter((contact) => !bKeys.has(keyFor(contact))) }; }, [left, right]);
  function select(side: "left" | "right", event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; const guard = guardFile(file, [".vcf", ".vcard"]); if (!guard.ok) { setStatus(guard.message); return; } const reader = new FileReader(); reader.onload = () => { if (reader.result instanceof ArrayBuffer) { const next = { name: file.name, text: decodeVCardBytes(reader.result).text }; side === "left" ? setLeft(next) : setRight(next); setStatus("Comparison preview updates when both files are selected"); } }; reader.onerror = () => setStatus("Could not read that file"); reader.readAsArrayBuffer(file); trackEvent("file_selected", { tool_slug: "compare-vcf-files", input_format: "vcf", size_bucket: file.size > 8 * 1024 * 1024 ? "large" : "standard" }); }
  function download() { if (!comparison) return; const report = [`VCF comparison report`, `Left contacts: ${comparison.a}`, `Right contacts: ${comparison.b}`, `Added: ${comparison.added.length}`, `Removed: ${comparison.removed.length}`, "", "Added contacts", ...comparison.added.map((contact) => `- ${contact.formattedName || "Unnamed contact"}`), "", "Removed contacts", ...comparison.removed.map((contact) => `- ${contact.formattedName || "Unnamed contact"}`)].join("\n"); const blob = new Blob([report], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "vcf-comparison-report.txt"; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); trackEvent("download_clicked", { tool_slug: "compare-vcf-files", output_format: "txt" }); }
  return <div className="comparison-card"><div className="comparison-toolbar"><div><strong>Compare two VCF files</strong><small aria-live="polite">{status}</small></div>{comparison && <button className="primary-button compact" onClick={download}>Download report <span>↓</span></button>}</div><div className="comparison-pickers"><label className="comparison-picker"><span>Original or older backup</span><strong>{left?.name || "Choose first VCF"}</strong><input type="file" accept=".vcf,.vcard,text/vcard" onChange={(event) => select("left", event)} /></label><label className="comparison-picker"><span>Newer or edited backup</span><strong>{right?.name || "Choose second VCF"}</strong><input type="file" accept=".vcf,.vcard,text/vcard" onChange={(event) => select("right", event)} /></label></div>{comparison && <div className="comparison-summary"><div><span>{comparison.a}</span><small>left contacts</small></div><div><span>{comparison.b}</span><small>right contacts</small></div><div><span>{comparison.added.length}</span><small>added</small></div><div><span>{comparison.removed.length}</span><small>removed</small></div></div>}</div>;
}

